addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - g++-4.8
      - gcc-4.8

compiler:
  - clang
  - gcc

install:
  - '[ "$CXX" = "g++" ] && export CXX="g++-4.8" CC="gcc-4.8"'

language: cpp

os:
  - linux

script: "./continuous.sh"

sudo: false
