addons:
  apt:
    packages:
      - clang-3.5
      - cmake
      - cmake-data
      - g++-4.9
      - gcc-4.9
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.5
      - ubuntu-toolchain-r-test

compiler:
  - clang
  - gcc

install:
  - '[ "$CXX" = "g++"     ] && export CXX="g++-4.9"     || :'
  - '[ "$CXX" = "clang++" ] && export CXX="clang++-3.5" || :'

language: cpp

os:
  - linux

script: "./continuous.sh"

sudo: false
