addons:
  apt:
    packages:
      - clang
      - cmake
      - cmake-data
      - g++-4.9
      - gcc-4.9
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test

compiler:
  - clang
  - gcc

install:
  - '[ "$CXX" = "g++" ] && export CXX="g++-4.9" CC="gcc-4.9" || :'

language: cpp

os:
  - linux

script: "./continuous.sh"

sudo: false
