version: '{build}'

install:
  - cmd: git submodule update --init --recursive

platform:
  - x86
  - x64

configuration: Debug

build:
  parallel: true
  verbosity: detailed

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..

build_script:
  - cmd: cmake --build .

test_script:
  - cmd: ctest --extra-verbose -C Debug

deploy: off
